import { expect, test, type Page } from "@playwright/test"
import type { MindMapReadResult, ShardMapFile } from "../../src/types"

test.use({ browserName: "webkit" })
type Harness = Window & { __mindMapDocumentMock: { disk: MindMapReadResult }; __mindMapDocumentHarness: { save(): Promise<boolean> } }
const topic = (page: Page, text: string) => page.getByRole("button", { name: `导图节点：${text}`, exact: true })
const editor = (page: Page) => page.locator('textarea[aria-label="导图节点"], textarea[aria-label="根节点"]')
const selected = (page: Page) => page.locator('[data-mind-map-node][aria-pressed="true"]')
async function saved(page: Page) {
  expect(await page.evaluate(() => (window as Harness).__mindMapDocumentHarness.save())).toBe(true)
  return page.evaluate(() => (window as Harness).__mindMapDocumentMock.disk.file)
}
const named = (file: ShardMapFile, text: string) => Object.values(file.nodes).find(node => node.text === text)!
const children = (file: ShardMapFile, text: string) => Object.values(file.nodes).filter(node => node.parentId === named(file, text).id).sort((a, b) => a.sortKey < b.sortKey ? -1 : a.sortKey > b.sortKey ? 1 : 0).map(node => node.text)
async function rename(page: Page, text: string) { await expect(editor(page)).toBeFocused(); await editor(page).fill(text); await editor(page).press("Escape") }

test("独立导图单击后 Enter 直接创建同级，大纲选中可前插同级和创建子主题", async ({ page }) => {
  await page.goto("/mind-map-document-test.html?mock=1")
  await topic(page, "主题甲").click()
  await expect(editor(page)).toHaveCount(0)
  await page.keyboard.press("Enter")
  await rename(page, "甲后同级")
  expect(children(await saved(page), "中心主题")).toEqual(["主题甲", "甲后同级", "主题乙", "主题丙"])
  await page.getByRole("button", { name: "显示检查器", exact: true }).click()
  await page.getByRole("tab", { name: "主题导航", exact: true }).click()
  await page.getByLabel("导图主题导航").getByRole("button", { name: "主题乙", exact: true }).click()
  await page.keyboard.press("Shift+Enter")
  await rename(page, "乙前同级")
  expect(children(await saved(page), "中心主题")).toEqual(["主题甲", "甲后同级", "乙前同级", "主题乙", "主题丙"])
  await topic(page, "主题乙").click()
  await page.keyboard.press("Tab")
  await rename(page, "乙的子主题")
  expect(children(await saved(page), "主题乙")).toEqual(["乙的子主题"])
  await page.getByRole("button", { name: "重新打开", exact: true }).click()
  await expect(topic(page, "乙的子主题")).toBeVisible()
  await expect(page.locator(".react-flow__node")).toHaveCount(0)
})

test("独立导图连续录入、空格和 F2 编辑、换行与 IME 边界", async ({ page }) => {
  await page.goto("/mind-map-document-test.html?mock=1")
  await topic(page, "主题甲").click()
  await page.keyboard.press("Space")
  await expect(editor(page)).toHaveValue("主题甲")
  await editor(page).fill("连续录入甲")
  await editor(page).press("Enter")
  await expect(editor(page)).toBeFocused()
  await editor(page).fill("连续录入乙")
  await editor(page).press("Tab")
  await rename(page, "连续录入子级")
  let file = await saved(page)
  expect(children(file, "连续录入乙")).toEqual(["连续录入子级"])
  await topic(page, "连续录入子级").click()
  await page.keyboard.press("F2")
  await editor(page).fill("第一行")
  await editor(page).press("End")
  await editor(page).press("Shift+Enter")
  await page.keyboard.insertText("第二行")
  await expect(editor(page)).toHaveValue("第一行\n第二行")
  await editor(page).dispatchEvent("keydown", { key: "Enter", isComposing: true, keyCode: 229 })
  await expect(editor(page)).toHaveValue("第一行\n第二行")
  await editor(page).press("ControlOrMeta+Enter")
  await expect(editor(page)).toHaveCount(0)
  file = await saved(page)
  expect(Object.values(file.nodes).filter(node => node.parentId === named(file, "连续录入乙").id)).toHaveLength(1)
})

test("独立导图父主题、方向键、排序、折叠和删除撤销维护树结构", async ({ page }) => {
  await page.goto("/mind-map-document-test.html?mock=1")
  await topic(page, "主题甲").click()
  await page.keyboard.press("ControlOrMeta+Enter")
  await rename(page, "甲的父主题")
  expect(children(await saved(page), "甲的父主题")).toEqual(["主题甲"])
  await page.keyboard.press("ArrowRight")
  await expect(selected(page)).toHaveAttribute("aria-label", "导图节点：主题甲")
  await page.keyboard.press("ArrowLeft")
  await page.keyboard.press("ControlOrMeta+/")
  await expect(topic(page, "主题甲")).toHaveCount(0)
  await page.keyboard.press("ArrowRight")
  await expect(topic(page, "主题甲")).toBeVisible()
  await topic(page, "主题乙").click()
  await page.keyboard.press("Alt+ArrowUp")
  expect(children(await saved(page), "中心主题")).toEqual(["主题乙", "甲的父主题", "主题丙"])
  await page.keyboard.press("Alt+ArrowDown")
  expect(children(await saved(page), "中心主题")).toEqual(["甲的父主题", "主题乙", "主题丙"])
  await topic(page, "甲的父主题").click()
  await page.keyboard.press("ControlOrMeta+Backspace")
  expect(children(await saved(page), "中心主题")).toEqual(["主题甲", "主题乙", "主题丙"])
  await page.keyboard.press("ControlOrMeta+z")
  await expect(topic(page, "甲的父主题")).toBeVisible()
  await topic(page, "甲的父主题").click()
  await page.keyboard.press("Delete")
  await expect(topic(page, "主题甲")).toHaveCount(0)
  await page.keyboard.press("ControlOrMeta+z")
  await expect(topic(page, "主题甲")).toBeVisible()
})
