import { expect, test } from "@playwright/test"

test.beforeEach(async ({ page }) => { await page.goto("/form-controls-test.html") })

test("自绘选项保留空值语义、标签、禁用与键盘，不触发父层快捷键", async ({ page }) => {
  const field = page.getByRole("combobox", { name: "字段", exact: true })
  await expect(field).toHaveText("未填写")
  await expect(page.locator("select,input[type=date],input[type=month],datalist")).toHaveCount(0)
  await field.focus(); await page.keyboard.press("Enter")
  await expect(page.getByRole("listbox")).toBeVisible()
  await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter")
  await expect(field).toHaveText("名称（主字段）")
  await expect(page.getByLabel("选择结果", { exact: true })).toHaveText("field-name")
  await field.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("listbox")).toBeVisible()
  await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter")
  await expect(field).toHaveText("名称（主字段）")
  await expect(page.getByRole("listbox")).toBeVisible()
  await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter")
  await expect(field).toHaveText("字段 1")
  await field.click(); await expect(page.getByRole("listbox")).toBeVisible(); await page.keyboard.press("Escape")
  await expect(field).toBeFocused()
  await expect(page.getByLabel("外层快捷键")).toHaveText("none")
  await expect(page.getByRole("combobox", { name: "禁用字段", exact: true })).toBeDisabled()
  await field.click(); await page.locator('[role="option"][data-value=""]').click()
  await expect(field).toHaveText("未填写")
})

test("真实DOM弹层具有Kiln样式并在窄窗口保留边界和长列表滚动", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 600 })
  const field = page.getByRole("combobox", { name: "字段", exact: true })
  const input = page.getByRole("textbox", { name: "参考输入框" })
  const styles = await field.evaluate(node => ({ radius: getComputedStyle(node).borderRadius, height: node.getBoundingClientRect().height, font: getComputedStyle(node).fontFamily }))
  expect(styles.radius).toBe("4px"); expect(styles.height).toBe(await input.evaluate(node => node.getBoundingClientRect().height)); expect(styles.font).toContain("Noto Sans SC")
  await field.click()
  const popup = page.locator('[data-slot="select-content"]')
  await expect(popup).toBeVisible()
  const rect = await popup.boundingBox(); const trigger = await field.boundingBox()
  expect(rect!.x).toBeGreaterThanOrEqual(0); expect(rect!.x + rect!.width).toBeLessThanOrEqual(390); expect(Math.abs(rect!.x - trigger!.x)).toBeLessThan(2)
  expect(await popup.evaluate(node => getComputedStyle(node).borderRadius)).toBe("6px")
  expect(await page.getByRole("listbox").evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true)
  await page.keyboard.press("End"); await page.keyboard.press("Enter")
  await expect(field).toContainText("字段 30")
  await field.click()
  await expect(page.locator('[role="option"][data-value="field-29"]')).toBeInViewport()
  await page.keyboard.press("Escape")
})

test("日历保留空值、闰日、年份边界、清空与键盘选择", async ({ page }) => {
  const trigger = page.getByRole("button", { name: "日期", exact: true })
  await trigger.click()
  await expect(page.getByLabel("日期结果")).toHaveText("empty")
  await page.getByRole("textbox", { name: "年份", exact: true }).fill("2024")
  await page.getByRole("combobox", { name: "月份", exact: true }).click()
  await page.getByRole("option", { name: "2 月", exact: true }).click()
  await page.getByRole("button", { name: "2024-02-29", exact: true }).click()
  await expect(trigger).toHaveText("2024-02-29"); await expect(trigger).toBeFocused()
  await trigger.click(); await expect(page.getByRole("button", { name: "2024-02-29", exact: true })).toBeFocused()
  await page.keyboard.press("ArrowRight"); await page.keyboard.press("Enter")
  await expect(trigger).toHaveText("2024-03-01")
  await trigger.click(); await page.getByRole("textbox", { name: "年份", exact: true }).fill("1")
  await page.getByRole("combobox", { name: "月份", exact: true }).click(); await page.getByRole("option", { name: "1 月", exact: true }).click()
  await expect(page.getByRole("button", { name: "上个月" })).toBeDisabled()
  await page.getByRole("button", { name: "0001-01-01", exact: true }).click(); await expect(trigger).toHaveText("0001-01-01")
  await trigger.click(); await page.getByRole("textbox", { name: "年份", exact: true }).fill("9999")
  await page.getByRole("combobox", { name: "月份", exact: true }).click(); await page.getByRole("option", { name: "12 月", exact: true }).click()
  await expect(page.getByRole("button", { name: "下个月" })).toBeDisabled()
  await page.getByRole("button", { name: "9999-12-31", exact: true }).click(); await expect(trigger).toHaveText("9999-12-31")
  await trigger.click(); await page.getByRole("button", { name: "清空", exact: true }).click()
  await expect(page.getByLabel("日期结果")).toHaveText("empty")
  await expect(page.getByLabel("外层快捷键")).toHaveText("none")
  await expect(page.getByRole("button", { name: "禁用日期", exact: true })).toBeDisabled()
})

test("弹层在父dialog内可交互，Escape只关闭当前层，composition不提交", async ({ page }) => {
  await page.getByRole("button", { name: "打开表单", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "控件弹窗" })
  const field = dialog.getByRole("combobox", { name: "弹窗字段" })
  await field.click(); await page.keyboard.press("ArrowDown")
  await page.locator('[role="option"][data-highlighted]').dispatchEvent("keydown", { key: "Enter", code: "Enter", keyCode: 229, isComposing: true })
  await expect(page.getByRole("listbox")).toBeVisible(); await expect(field).toHaveText("未填写")
  await page.keyboard.press("Escape"); await expect(dialog).toBeVisible(); await expect(field).toBeFocused()
  await dialog.getByRole("button", { name: "弹窗日期" }).click()
  await page.keyboard.press("Escape")
  await expect(page.locator('[data-slot="date-picker-content"]')).toHaveCount(0); await expect(dialog).toBeVisible()
})

test("日历在窄窗内完整显示，浏览月份与无效年份不会写入日期", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 600 })
  const trigger = page.getByRole("button", { name: "日期", exact: true })
  await trigger.click()
  const popup = page.locator('[data-slot="date-picker-content"]')
  const bounds = await popup.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(600)
  expect(await popup.evaluate(node => ({ width: node.scrollWidth, visible: node.clientWidth }))).toEqual({ width: Math.round(bounds!.width), visible: Math.round(bounds!.width) })
  await page.getByRole("button", { name: "下个月" }).click()
  await page.getByRole("textbox", { name: "年份", exact: true }).fill("10000")
  await expect(page.getByRole("textbox", { name: "年份", exact: true })).toHaveAttribute("aria-invalid", "true")
  await expect(page.getByLabel("日期结果")).toHaveText("empty")
  await page.keyboard.press("Escape")
  await expect(trigger).toBeFocused(); await expect(trigger).toHaveText("选择日期")
  await page.keyboard.press("Escape")
  await expect(page.getByLabel("外层快捷键")).toHaveText("Escape")
})
